### ISSUE TITLE
Explanation Section: `att` explanation disappears for some UCANs

### ISSUE THREAD

**Issue by matheus23** [ucan-wg/ucan-check#10]
It seems like there's one row that explains `att` in the "Explanation" section for each capability in the `att`.

E.g. if I paste in this UCAN: `eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCIsInVjdiI6IjAuNy4wIn0.eyJhdWQiOiJkaWQ6a2V5Ono2TWtmZkRaQ2tDVFdyZWc4ODY4ZkcxRkdGb2djSmo1WDZQWTkzcFBjV0RuOWJvYiIsImF0dCI6W10sImV4cCI6MTYzOTY1MDEzNSwiaXNzIjoiZGlkOmtleTp6Nk1razg5YkMzSnJWcUtpZTcxWUVjYzVNMVNNVnh1Q2dOeDZ6TFo4U1lKc3hBTGkiLCJuYmYiOjE2Mzk2NTAwNDUsInByZiI6W119.1UizuPBOw1v-wa7YTvBs5v_L108qamKo5YQOmlnCCH0AKv0l2vftDw7CIMBwStv4ncuaRtnJ6WL6YspDSN4VAg`,
which has `att: []`, then there's no explainer row for `att`.

And for the example UCAN that you get when you press `Show Example` you get two `att` explainers:
![image](https://user-images.githubusercontent.com/1430958/146354728-c20b3d13-c411-4efa-8c7e-c90d6be20dc8.png)

**Comment by bgins** [comment]
Yeah, this could be improved, thanks for catching it. 🙏 

Maybe we should show the raw `att` value as a JSON string for the value here? We could also experiment with some custom formatting if attenuations generally have some consistent shape.

I may be remembering incorrectly, but I think the [StructuredList](https://carbon-components-svelte.onrender.com/components/StructuredList) component we use here only works well with strings. We can experiment with it, and if it doesn't work out, customize the component.

**Comment by matheus23** [comment]
> Maybe we should show the raw att value as a JSON string for the value here? We could also experiment with some custom formatting if attenuations generally have some consistent shape.

Yep. I have a PR coming up in which that's what I've decided so far.

**Comment by bgins** [comment]
Fixed in #14.
