### ISSUE TITLE
Code blocks render with an extra indent on the first line

### ISSUE THREAD

**Issue by QuinnWilton** [ucan-wg/ucan-check#27]
![image](https://user-images.githubusercontent.com/285821/158471933-8fb07af9-9dde-4bf5-acec-8e9ff4412788.png)

This happens because of the way the `code` tag is nested within a `pre` tag:
```html
<pre>
        <code>{
  "alg": "EdDSA",
  "typ": "JWT",
  "ucv": "0.7.0"
}</code>
      </pre>
```

**Comment by bgins** [comment]
This indent issue was fixed in https://github.com/ucan-wg/ucan-check/pull/25.

The GH action [failed to publish](https://github.com/ucan-wg/ucan-check/actions/runs/1983563619) the updated version of the site due to an invalid key file. Once that is fixed, we should be good to go.

**Comment by QuinnWilton** [comment]
Awesome, thanks! I noticed this while showing the site off to someone today and didn't think to check whether it'd been fixed but yet to be deployed.

**Comment by bgins** [comment]
Kind of confusing to be honest. No open PRs with fixes, merged ones should be published. 

So thanks for opening the issue, always good to have more visibility on it. 🙏

**Comment by bgins** [comment]
GH actions have been on and off today. Went ahead and published this fix manually from the CLI. Indentation should be good now!
