### ISSUE TITLE
Deep links to non-root routes fail to resolve

### ISSUE THREAD

**Issue by QuinnWilton** [ucan-wg/ucan-check#28]
Directly trying to visit a route other than `/`, like https://ucan.xyz/validator, results in the following error:

```
ipfs resolve -r /ipns/ucan.xyz/validator: no link named "validator" under bafybeieuab23xr354rzq2pwgmennxoj7wlfzmyvyko74a7ewfbfcyzv3re
```

I imagine this happens because the application is only actually being served from the root, and normally relies on Svelte to conditionally render the route based on the current pathname. A quick and dirty fix might be to just change the routes to use hash routing, so that directly visiting the validator -- possibly through a refresh -- still makes a request to `/`.

**Comment by walkah** [comment]
This is fixed
